worker_processes 2;
events{
    worker_connections 1024 ;
}
http{
     log_format main '$remote_addr "$request" '
                    'upstream=$upstream_addr '
                    'status=$status';

    access_log /var/log/nginx/access.log main;
    upstream backend{
        server app1:8080;
        server app2:8080;
        server app3:8080;
    }
    server{
    listen 80;
    location / {
    proxy_pass http://backend;
    }
    }
}
